export const REPO = {
  COURSE: 'COURSE_REPOSITORY',
  MOD: 'MOD_REPOSITORY',
  MOD_GROUP: 'MOD_GROUP_REPOSITORY',
  PROFILE: 'PROFILE_REPOSITORY'
};

export const CONFIG = {
  DATABASE_URL: 'DATABASE_URL'
};

export const SEQUELIZE = 'SEQUELIZE';

export const JWT = {
  SECRET: 'JWT_SECRET'
};